ALTER TABLE loans
ADD COLUMN paid_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN next_payment_date DATE,
ADD COLUMN payment_day INT,
ADD COLUMN user_id INTEGER REFERENCES users(id),
ADD COLUMN loan_name VARCHAR(255),
ADD COLUMN loan_type VARCHAR(50);
